### ISSUE TITLE
Export BDD

### ISSUE THREAD

**Issue by adricen** [laurianne29/site-cv#1]
### Salut Laurianne29

Tu pourrais exporter ta bdd stp?

Comme ça je pourrais intervenir sur ton projet et te filer coups de mains et conseil 

Merci ;)

**Comment by laurianne29** [comment]
BDD uploadé !

Bonne soirée

**Comment by laurianne29** [comment]
BDD uploadé !

Bonne soirée

**Comment by adricen** [comment]
À la racine!

*Parfait*

Bonne soirée !
